<a href="https://colab.research.google.com/github/ZYD-9/Learn_Pytorch/blob/main/Pytorch_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

 **Tensors**

 Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters,tensors can run on GPUs or other hardware accelerators.

from: Pytorch Documentation

In [ ]:
data = [[1,2,5],[3,4,7],[5,6,9]]
tensored_data = torch.tensor(data)
print(tensored_data)

tensor([[1, 2, 5],
        [3, 4, 7],
        [5, 6, 9]])


In [ ]:
np_array = np.array(data)
x_data = torch.from_numpy(np_array)
print(x_data)

tensor([[1, 2, 5],
        [3, 4, 7],
        [5, 6, 9]])


New tensor will retain the properties of the data these properties are its shape and datatype, however it can changed if overridden.
 The 'torch.ones_like' code Returns a tensor filled with the scalar value 1 , with the same size as input .

In [ ]:
data_ones = torch.ones_like(tensored_data)
print(data_ones)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


The code 'torch.rand_like Returns a tensor with the same size as input that is filled with random numbers from a uniform distribution on the interval [ 0 , 1 ) [0, 1) [0,1).

In [ ]:
data_rand = torch.rand_like(tensored_data, dtype = torch.float) # overrides the original data from int to float
print(data_rand)

tensor([[0.3589, 0.6101, 0.0071],
        [0.5886, 0.5712, 0.0842],
        [0.7981, 0.3883, 0.0312]])


torch.rand() is used to create a tensor with the random values from the uniform distribution that lies between the interval [0,1)

In [ ]:
data_shape = (3,3)
ones_tensor = torch.ones(data_shape)
rand_tensor = torch.rand(data_shape)
zero_tensor = torch.zeros(data_shape)

print(ones_tensor)
print(rand_tensor)
print(zero_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.0015, 0.7659, 0.5715],
        [0.8596, 0.4996, 0.9857],
        [0.2339, 0.1010, 0.6724]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
